development:
  cloud_name: "dljiokqzl"
  api_key: "686938429345529"
  api_secret: "FSBybfsNJzCM5IHbT_dw4xCFWzk"
  secure: true
  cdn_subdomain: true
  enhance_image_tag: true
  static_file_support: false

production:
  cloud_name: "dljiokqzl"
  api_key: "686938429345529"
  api_secret: "FSBybfsNJzCM5IHbT_dw4xCFWzk"
  secure: true
  cdn_subdomain: true
  enhance_image_tag: true
  static_file_support: true
